# Generated by Django 5.0.14 on 2026-05-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-')], max_length=50, null=True),
        ),
    ]
