# Generated by Django 5.0.14 on 2026-05-18 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('degree', models.CharField(max_length=150)),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('PEDIATRICS', 'Pediatrics'), ('GENERAL_MEDICINE', 'General Medicine'), ('ORTHOPEDICS', 'Orthopedics'), ('GYNECOLOGY', 'Gynecology'), ('NEUROLOGY', 'Neurology'), ('OPHTHALMOLOGY', 'Ophthalmology')], max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
                ('medical_council_number', models.CharField(max_length=50, unique=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='identity_docs/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('consultation_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('languages_spoken', models.CharField(default='English, Hindi', max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.TextField()),
                ('clinic_city', models.CharField(max_length=100)),
                ('clinic_pin_code', models.CharField(max_length=10)),
                ('clinic_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clinic_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
